{% set version = "1.4" %}

package:
  name: blinker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blinker/blinker-{{ version }}.tar.gz
  sha256: 471aee25f3992bd325afa3772f1063dbdbbca947a041b8b89466dc00d606f8b6

build:
  number: 0
  script: echo x86 # [x86]
  script: echo x86_64 # [x86_64]
  script: echo linux # [linux]
  script: echo linux32 # [linux32]
  script: echo linux64 # [linux64]
  script: echo armv6l # [armv6l]
  script: echo armv7l # [armv7l]
  script: echo aarch64 # [aarch64]
  script: echo ppc64le # [ppc64le]
  script: echo s390x # [s390x]
  script: echo arm64 # [arm64]
  script: echo unix # [unix]
  script: echo win # [win]
  script: echo win32 # [win32]
  script: echo win64 # [win64]


requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - blinker

about:
  home: http://pythonhosted.org/blinker/
  license: MIT
  license_file: LICENSE
  summary: Fast, simple object-to-object and broadcast signaling

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
