{% set name = "blinker" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blinker-{{ version }}.tar.gz
  sha256: b4ce2265a7abece45e7cc896e98dbebe6cead56bcf805a3d23136d145f5445bf
  patches:
    # Add asyncio fixture to test_async_receiver
    - 187.patch

build:
  number: 1
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - blinker
  requires:
    - pip
    - pytest
    # pytest-asyncio 1.0.0 is not compatible with blinker 1.9.0.
    # Replace it with pytest-tornasync for now.
    #- pytest-asyncio
    - pytest-tornasync
  commands:
    - pip check
    - pytest --pyargs tests -vv

about:
  home: https://blinker.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Fast, simple object-to-object and broadcast signaling
  description: |
    Blinker provides fast & simple object-to-object and broadcast
    signaling for Python objects.
  dev_url: https://github.com/pallets-eco/blinker
  doc_url: https://blinker.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
