travis:
  secure:
    BINSTAR_TOKEN: j3aqMlBNgkf0+t9CeAI0BKZanFH7WBdApns19F4RcjdjvzYPaOkBIoZYHaUhufsZ9pWs9DB+bZfYoXBBNj1e5IqxmM1qniWk7f+C0tLYQz6gpO6PGazzlOfkmalOpu7guUCBk6CDcQ5HcFzSo6cBbb/h7tjizATQBZR8aUQ1wT3qKoPdsqK2AWH1qHCjzpu0t4rvBZUy7Z0nO1pD0ksu9O9UUXYtfQUi/2Ba3/ssqvAG1zUkRAyZhn/hosJt0NfBTmHaObWWCER7D4tVkmLY17Vll9iHyXZsRhwf7zce1MQxuJV1nRG9Y+xiimMbhrlP13Fc8fqvlgYPH6OQ6+uZip9uv22rEhq+y0OorayswchiEewgt4Cd+3MBchwXnTk95QFgoABn1n51NyLnZGR3oQL4n4G2ZYrhMuWn40OA7wINqyfBvQaYyHC6MH8rYVg9sXAQzxbvS0gpTzQerR9wykIxs/Zc9dwMIpFArvy8PQ6rcA+Gve9LXlu/YWybTPLJKkMP+UUsYnnIrq7gz3d8LdiSX+rmEARN7h+MIcBwzwSq4fi/yokS2g2Z3bBp1/od+AcjIIoYT7dL3IDUCOXVvlDgswtGQyus5MnzYLtLYfXFUIwsniC4oHt5aR/XJwb8oq06+7o88zY70zdoFpkjqvkWOKMXAXdmp7xpdrbnxVU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
